In [29]:
import numpy as np
import pandas as pa
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential 
from keras.layers import Dense 
from keras.optimizers import *
from keras.utils import *
import warnings
from sklearn.model_selection import GridSearchCV

#dataset import
colnames=['e/p','cap-shape', 'cap-surface', 'cap-color', 'bruises?', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring', 'stalk-color-below-ring', 'veil-type', 'veil-color','ring-number', 'ring-type', 'spore-print-color', 'population', 'habitat'] 
dataset = pa.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data", names=colnames, header=0)

#oneHOtEncoding
labels = colnames
categorical_data = dataset[labels]
ohe = OneHotEncoder(categories='auto')
feature_arr = ohe.fit_transform(categorical_data).toarray()
ohe_labels = ohe.get_feature_names_out(labels)
features = pa.DataFrame(feature_arr,columns=ohe_labels)

print(features)

x= features.iloc[:, -117:].values
Y=features.iloc[:, :-117].values

x_train,x_test, Y_train,Y_test = train_test_split(x, Y, test_size=0.3)

num_classes = Y_train.shape[1]
print(num_classes)

def neural_network():
    model = Sequential()
    model.add(Dense(117, input_dim=117, kernel_initializer='normal', activation='relu'))
    model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

param_grid= {'n_estimators':[100,200,300,400,500,600,700,800,900,1000],
    'criterion':['gini','entropy'],
    'max_depth': [2,3]}

model = neural_network()
grid_search = GridSearchCV(model, param_grid=param_grid, cv=10, scoring='f1_macro', n_jobs=4)
model.summary()


warnings.filterwarnings("ignore")

model.fit(x_train, Y_train, validation_data=(x_test, Y_test), epochs=1, batch_size=100)

scores = model.evaluate(x_test, Y_test)
print("Neural network accuracy: %.2f%%" % (scores[1]*100))


      e/p_e  e/p_p  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  \
0       1.0    0.0          0.0          0.0          0.0          0.0   
1       1.0    0.0          1.0          0.0          0.0          0.0   
2       0.0    1.0          0.0          0.0          0.0          0.0   
3       1.0    0.0          0.0          0.0          0.0          0.0   
4       1.0    0.0          0.0          0.0          0.0          0.0   
...     ...    ...          ...          ...          ...          ...   
8118    1.0    0.0          0.0          0.0          0.0          1.0   
8119    1.0    0.0          0.0          0.0          0.0          0.0   
8120    1.0    0.0          0.0          0.0          1.0          0.0   
8121    0.0    1.0          0.0          0.0          0.0          1.0   
8122    1.0    0.0          0.0          0.0          0.0          0.0   

      cap-shape_s  cap-shape_x  cap-surface_f  cap-surface_g  ...  \
0             0.0          1.0            

In [6]:
import numpy as np
import pandas as pa
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential 
from keras.layers import Dense 
from keras.optimizers import *
from keras.utils import *
import warnings
from sklearn.model_selection import GridSearchCV

import numpy as np
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split

#dataset import
colnames=['e/p','cap-shape', 'cap-surface', 'cap-color', 'bruises?', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring', 'stalk-color-below-ring', 'veil-type', 'veil-color','ring-number', 'ring-type', 'spore-print-color', 'population', 'habitat'] 
dataset = pa.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data", names=colnames, header=0)

#oneHOtEncoding
labels = colnames
categorical_data = dataset[labels]
ohe = OneHotEncoder(categories='auto')
feature_arr = ohe.fit_transform(categorical_data).toarray()
ohe_labels = ohe.get_feature_names_out(labels)
features = pa.DataFrame(feature_arr,columns=ohe_labels)

print(features)

x= features.iloc[:, -117:].values
Y=features.iloc[:, :-117].values

x_train,x_test, Y_train,Y_test = train_test_split(x, Y, test_size=0.3)

num_classes = Y_train.shape[1]
print(num_classes)

def neural_network():
    model = Sequential()
    model.add(Dense(117, input_dim=117, kernel_initializer='normal', activation='relu'))
    model.add(Dense(num_classes, kernel_initializer='normal', activation='softmax'))    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

param_grid= {'n_estimators':[100,200,300,400,500,600,700,800,900,1000],
    'criterion':['gini','entropy'],
    'max_depth': [2,3]}

model = neural_network()
grid_search = GridSearchCV(model, param_grid=param_grid, cv=10, scoring='f1_macro', n_jobs=4)
model.summary()


warnings.filterwarnings("ignore")

model.fit(x_train, Y_train, validation_data=(x_test, Y_test), epochs=1, batch_size=100)

scores = model.evaluate(x_test, Y_test)
print("Neural network accuracy: %.2f%%" % (scores[1]*100))






[[[[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]]



 [[[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]]



 [[[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]]



 ...



 [[[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]]



 [[[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]


  [[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]]



 [[[[0. 1.]
    [1. 0.]]

   [[1. 0.]
    [0. 1.]]]


  [[[1. 0.]
    [0. 1.]]

   [[0. 1.]
    [1. 0.]]]]]
